### ISSUE TITLE
Social media profiles – link list + CSS

### ISSUE THREAD

**Issue by nfreear** [nfreear/nfreear.github.io#18]
* http://freear.org.uk/nick#!_ul.profile

SCSS/SASS mixin:
```scss
@mixin icon ($domain, $favicon) {

    & [ href *= "#{$domain}" ] {
        background-image: url($favicon);
    }
}
```

Usage -- SCSS:
```scss
.pg-profile {

    ul:nth-of-type( 1 ) {
        margin: 1.7em 10px;
        list-style: none;
    }

    ul:nth-of-type( 1 ) a[ href *= ":" ] {
        padding-left: 30px;
        background-repeat: no-repeat;
        background-position: left;
        background-size: 18px 18px;
    }

    @include icon( "open.ac.uk", "http://www3.open.ac.uk/favicon.ico" );

// ...
}
```
