### ISSUE TITLE
Integrate & blog about 'sign-machine'; ability for a post to add a 'footer-script'

### ISSUE THREAD

**Issue by nfreear** [nfreear/nfreear.github.io#24]
..

* `sign-machine` repository ~ https://github.com/nfreear/sign-machine
* A proposal for an `x-footer-script` property in the YAML front-matter for a post/ page ...
* I should document all the custom front-matter properties !!

```yaml
---
layout: post
title:  Sign-machine rebooted
date:   2017-05-22 17:23
# ...
x-footer-script: https://cdn.rawgit.com/nfreear/sign-machine/2.0-alpha/src/sign-machine.js
---
```
