### ISSUE TITLE
Redirection via Javascript ...

### ISSUE THREAD

**Issue by nfreear** [nfreear/nfreear.github.io#27]
YAML front matter in page:

```yaml
---
# ...

x-redirect-url: /2017/05/22/sign-machine.html
x-hash: '#id-sign-machine'
---
```

---
`includes/head.html`:

```html
{% if page.x-redirect-url %}
  <script>
  setTimeout(function () {
    var x_redirect_url = '{{ page.x-redirect-url }}' + ( location.search || '?' ) + '&utm_source=redirect' + '{{ page.x-hash }}';
    // console.log(x_redirect_url);
    window.location = x_redirect_url;
  }, 2000 );
  </script>
  <p role="alert" class="big_me"> Redirecting ... </p>
{% endif %}
```
